name: opencood
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.11
  - pip=21.3.1
  - setuptools<66
  - wheel
  - numpy
  - matplotlib=3.4.2
  - cython
  - shapely=1.8.5
  - einops
  - pip:
      - pygame==2.1.2
      - open3d==0.16.0
      - opencv-python==4.5.5.64
      - tensorboardX
      - cumm
      - "timm==0.6.13"